# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 03:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_description', models.CharField(max_length=200, unique=True)),
                ('link_url', models.CharField(max_length=1000, unique=True)),
                ('add_date', models.DateTimeField(verbose_name='date_added')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=200)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memCall.UserProfile', to_field='user'),
        ),
        migrations.AddField(
            model_name='link',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memCall.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('topic_title', 'user')]),
        ),
    ]
