# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memCall', '0002_auto_20160718_2106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([]),
        ),
    ]
