# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memCall', '0005_topic_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memCall.UserProfile', to_field='user'),
        ),
    ]
