# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_description', models.CharField(max_length=200)),
                ('link_url', models.CharField(max_length=1000)),
                ('add_date', models.DateTimeField(verbose_name='date_added')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.Topic'),
        ),
    ]
